#!/usr/bin/env python
import argparse
import os
import sys

parser = argparse.ArgumentParser(description='Script to illustrate basic usage of argparse to process arguments')
   
# Add arguments for input and output files
parser.add_argument('arg1', type=str, help='Path to the input file.')
parser.add_argument('arg2', type=str, help='Name for the output file.')
parser.add_argument('arg3', type=str, help='Path for saving the output file.')

# Parse the command-line arguments
args = parser.parse_args()
  

input_filepath = args.arg1 #"/home/akram/Documents/data/bam/tNCC_Day7_Input_S31_R1_001.ht2.srt.bam"
output_filename = args.arg2
output_dir = os.path.dirname(args.arg3)
print(f"Input: {input_filepath}")
print(f"Saving {output_filename} into {output_dir}")

with open(input_filepath,'r') as input_file:
    sample = input_file.readlines()[:10] # Read the first 10 lines
    
    
    
# Open a file in write mode
with open(os.path.join(output_dir,output_filename),'w') as f:
    # Redirect standard output to the file
    sys.stdout = f
    print(f"""
          This is a test file generated by the {__file__} script.
          Printing the first lines of the file: {input_filepath}
          """)
    
    print(sample)
    
# Reset standart output
sys.stdout = sys.__stdout__



